apiVersion: v1
kind: Service
metadata:
  name: spring-demo-service
spec:
  type: NodePort
  selector:
    app: spring-demo
  ports:
    - port: 8888        # порт внутри кластера
      targetPort: 8888  # порт контейнера
      nodePort: 30080   # наружу на VDS
