name: CI/CD to Minikube

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: podkmax/spring-minikube-demo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: ./mvnw package -DskipTests

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Copy Kubernetes manifests to VDS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.VDS_SSH_KEY }}
          source: "k8s/*.yaml"
          target: "/home/${{ secrets.VDS_USER }}/k8s/"

      - name: Deploy to Minikube via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.VDS_SSH_KEY }}
          envs: IMAGE_NAME
          script: |
            docker pull $IMAGE_NAME
            kubectl apply -f /home/${{ secrets.VDS_USER }}/k8s/deployment.yaml
            kubectl apply -f /home/${{ secrets.VDS_USER }}/k8s/service.yaml